version: "3.9"

networks:
  rabbitmq-net:
    driver: bridge

services:
  rabbitMQ:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    expose:
      - 15692
    ports:
        - "5672:5672"
        - "15672:15672"
        - "15692:15692"
    networks:
      - rabbitmq-net
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin